
Brewery.create!([
  {name: "Birdsong Brewing Company", location: "1016 North Davidson Street", description: "", rating: nil, website: "ll", neighborhood: "Noda", wifi: "Yes", live_music: "", pet_friendly: "", dining: "", outdoor_seating: "", phone_number: "", food_trucks: "", image_file_name: "He-man.jpg", image_content_type: "image/jpeg", image_file_size: 748441, image_updated_at: "2016-08-25 15:00:09"},
  {name: "Free Range Brewing ", location: "2320 North Davidson Street", description: "", rating: nil, website: "", neighborhood: "", wifi: "yes", live_music: "", pet_friendly: "", dining: "", outdoor_seating: "", phone_number: "", food_trucks: "", image_file_name: "He-man.jpg", image_content_type: "image/jpeg", image_file_size: 748441, image_updated_at: "2016-08-25 15:05:38"},
  {name: "Heist Brewery", location: "2909 North Davidson Street", description: "", rating: nil, website: "heistbrewery.com", neighborhood: "Noda", wifi: "Yes", live_music: "Yes", pet_friendly: "Yes", dining: "Yes", outdoor_seating: "Yes", phone_number: "(704)-375-8260", food_trucks: "No", image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil},
  {name: "Leigon Brewing", location: "1906 Commonwealth Ave", description: "", rating: nil, website: "legionbrewing.com", neighborhood: "Elizabeth", wifi: "No", live_music: "Yes", pet_friendly: "Yes", dining: "No", outdoor_seating: "Yes", phone_number: "", food_trucks: "No", image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil},
  {name: "Lenny Boy Brewing Co.", location: "2224 Hawkings Street", description: "", rating: nil, website: "discoverlennyboy.com", neighborhood: "South End", wifi: "No", live_music: "No", pet_friendly: "Yes", dining: "No", outdoor_seating: "No", phone_number: "(980)-585-1728", food_trucks: "Yes", image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil},
  {name: "Noda Brewing Co.", location: "2229 North Davidson Street", description: "", rating: nil, website: "nodabrewing.com/the-beer", neighborhood: "Noda", wifi: "No", live_music: "No", pet_friendly: "Yes", dining: "No", outdoor_seating: "Yes", phone_number: "(704)-900-6851", food_trucks: "Yes", image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil},
  {name: "Rock Bottom Restaurant & Brewery ", location: "401 North Tryon Street Suite 100", description: "", rating: nil, website: "rockbottomsouth.com", neighborhood: "Fourth Ward", wifi: "Yes", live_music: "No", pet_friendly: "No", dining: "Yes", outdoor_seating: "Yes", phone_number: "(704)-334-2739", food_trucks: "No", image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil},
  {name: "Salud Beer Shop", location: "3306-B North Davidson Street", description: "", rating: nil, website: "saludbeershop.com", neighborhood: "Noda", wifi: "No", live_music: "No", pet_friendly: "No", dining: "No", outdoor_seating: "No", phone_number: "(704)-900-7767", food_trucks: "No", image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil},
  {name: "Sugar Creek Brewing Company", location: "215 Southside Drive ", description: "", rating: nil, website: "sugarcreekbrewing.com", neighborhood: "South End", wifi: "No", live_music: "Yes", pet_friendly: "Yes", dining: "No", outdoor_seating: "Yes", phone_number: "(704)-521-3333", food_trucks: "Yes", image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil},
  {name: "Sycamore Brewing ", location: "2161 Hawkins Street", description: "", rating: nil, website: "sycamorebrew.com", neighborhood: "South End", wifi: "No", live_music: "Yes", pet_friendly: "Yes", dining: "No", outdoor_seating: "Yes", phone_number: "(704)-910-3821", food_trucks: "Yes", image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil},
  {name: "Olde Mecklenburg Brewing", location: "4150 Yancey Road", description: "", rating: nil, website: "oldemeckbrew.com", neighborhood: "", wifi: "No", live_music: "Yes", pet_friendly: "Yes", dining: "Yes", outdoor_seating: "Yes", phone_number: "(704)-525-5644", food_trucks: "No", image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil},
  {name: "Three Spirits Brewery", location: "5046 Old Pineville Road", description: "", rating: nil, website: "threespirtsbrewery.com", neighborhood: "Starmount", wifi: "No", live_music: "Yes", pet_friendly: "Yes", dining: "No", outdoor_seating: "Yes", phone_number: "(980)-207-4881", food_trucks: "No", image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil},
  {name: "Triple C Brewing Company", location: "2900 Griffith Street", description: "", rating: nil, website: "triplecbrewing.com", neighborhood: "", wifi: "No", live_music: "Yes", pet_friendly: "Yes", dining: "No", outdoor_seating: "Yes", phone_number: "(704)-372-3212", food_trucks: "Yes", image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil},
  {name: "Unknown Brewing ", location: "1327 South Mint Street", description: "", rating: nil, website: "www.unknownbrewing.com", neighborhood: "", wifi: "No", live_music: "No", pet_friendly: "No", dining: "No", outdoor_seating: "No", phone_number: "(980)-237-2628", food_trucks: "No", image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil},
  {name: "Wooden Robot Brewery", location: "1440 South Tryon Street", description: "", rating: nil, website: "woodenrobotbrewery.com", neighborhood: "South End ", wifi: "No", live_music: "No", pet_friendly: "Yes", dining: "Yes", outdoor_seating: "Yes", phone_number: "(980)-819-7875", food_trucks: "Yes", image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil}
])
